// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.infra.Context;

namespace Projeto.infra.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20210615023845_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DividaParcelas", b =>
                {
                    b.Property<int>("DividasIdTitulo")
                        .HasColumnType("int");

                    b.Property<int>("ParcelasIdParcela")
                        .HasColumnType("int");

                    b.HasKey("DividasIdTitulo", "ParcelasIdParcela");

                    b.HasIndex("ParcelasIdParcela");

                    b.ToTable("DividaParcelas");
                });

            modelBuilder.Entity("Teste.FullSatck.Domain.Entities.Divida", b =>
                {
                    b.Property<int>("IdTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Juros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NmDevedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrDevedor")
                        .HasColumnType("int");

                    b.Property<int>("NrParcelas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("VlParcela")
                        .HasColumnType("int");

                    b.HasKey("IdTitulo");

                    b.ToTable("Divida");
                });

            modelBuilder.Entity("Teste.FullSatck.Domain.Entities.Parcelas", b =>
                {
                    b.Property<int>("IdParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativos")
                        .HasColumnType("bit");

                    b.Property<int>("NrParcelas")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdParcela");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("Teste.FullSatck.Domain.Entities.TitulosAtraso", b =>
                {
                    b.Property<int>("IdAtraso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiaAtraso")
                        .HasColumnType("int");

                    b.Property<int>("DtdeParc")
                        .HasColumnType("int");

                    b.Property<string>("NmDevedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrTitulo")
                        .HasColumnType("int");

                    b.Property<decimal>("VlAtrsado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VlParc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAtraso");

                    b.ToTable("TitulosAtrasos");
                });

            modelBuilder.Entity("DividaParcelas", b =>
                {
                    b.HasOne("Teste.FullSatck.Domain.Entities.Divida", null)
                        .WithMany()
                        .HasForeignKey("DividasIdTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teste.FullSatck.Domain.Entities.Parcelas", null)
                        .WithMany()
                        .HasForeignKey("ParcelasIdParcela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
